on:
  push:
    branches:
      - 3.x
  pull_request: null

name: testo

jobs:
  testo:
    uses: spiral/gh-actions/.github/workflows/testo.yml@master
    with:
      os: >-
        ['ubuntu-latest']
